- name:  Server Hardening
  hosts: ubuntu-server
  gather_facts: no
  sudo: yes
  roles:
    - sshd
  tags:
    - sshd

- name:  MOTD Customization
  hosts: ubuntu-server
  gather_facts: no
  sudo: yes
  roles:
    - motd
  tags:
    - motd

